from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Literal

# Keep category names consistent with mapgen.rag.inventory.CATEGORIES.
CATEGORIES = ["非遗", "历史人物", "建筑地标", "民俗节庆", "饮食", "自然景观", "产业符号"]

StoryboardTone = Literal["文化宣传", "童话叙事", "旅行导览", "历史讲述"]
ShotType = Literal["开场", "过渡", "文化展示", "人物行动", "结尾"]
PromptType = Literal["image", "animation"]


@dataclass(slots=True)
class SourceRef:
    """Source information inherited from the culture inventory / RAG results."""

    title: str = ""
    url: str = ""

    @classmethod
    def from_dict(cls, data: dict[str, Any] | None) -> "SourceRef":
        data = data or {}
        return cls(title=str(data.get("title", "")).strip(), url=str(data.get("url", "")).strip())

    def to_dict(self) -> dict[str, str]:
        return asdict(self)


@dataclass(slots=True)
class CultureElementRef:
    """A cultural element selected from A's inventory for one storyboard scene."""

    place_name: str
    element_name: str
    category: str = "产业符号"
    summary: str = ""
    visual_keywords: list[str] = field(default_factory=list)
    usage_suggestions: list[str] = field(default_factory=list)
    confidence: float = 0.5
    sources: list[SourceRef] = field(default_factory=list)

    @classmethod
    def from_inventory_item(cls, item: dict[str, Any]) -> "CultureElementRef":
        confidence = item.get("confidence", 0.5)
        try:
            confidence = float(confidence)
        except (TypeError, ValueError):
            confidence = 0.5

        return cls(
            place_name=str(item.get("place_name", "")).strip(),
            element_name=str(item.get("element_name", "")).strip(),
            category=normalize_category(item.get("category", "产业符号")),
            summary=str(item.get("summary", "")).strip(),
            visual_keywords=string_list(item.get("visual_keywords", [])),
            usage_suggestions=string_list(item.get("usage_suggestions", [])),
            confidence=max(0.0, min(1.0, confidence)),
            sources=[SourceRef.from_dict(src) for src in item.get("sources", []) if isinstance(src, dict)],
        )

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["sources"] = [source.to_dict() for source in self.sources]
        return data


@dataclass(slots=True)
class StoryboardScene:
    """One scene in the storyboard generated by B."""

    scene_id: int
    title: str
    culture_element: CultureElementRef
    shot_type: ShotType = "文化展示"
    duration_seconds: float = 8.0
    map_reference: str = ""
    visual_description: str = ""
    character_action: str = ""
    camera_movement: str = ""
    transition: str = ""
    narration: str = ""
    style_notes: list[str] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "StoryboardScene":
        element = data.get("culture_element", {})
        if isinstance(element, CultureElementRef):
            culture_element = element
        elif isinstance(element, dict):
            culture_element = CultureElementRef.from_inventory_item(element)
        else:
            culture_element = CultureElementRef(place_name="", element_name=str(element).strip())

        return cls(
            scene_id=int(data.get("scene_id", 0)),
            title=str(data.get("title", "")).strip(),
            culture_element=culture_element,
            shot_type=normalize_shot_type(data.get("shot_type", "文化展示")),
            duration_seconds=positive_float(data.get("duration_seconds", 8.0), default=8.0),
            map_reference=str(data.get("map_reference", "")).strip(),
            visual_description=str(data.get("visual_description", "")).strip(),
            character_action=str(data.get("character_action", "")).strip(),
            camera_movement=str(data.get("camera_movement", "")).strip(),
            transition=str(data.get("transition", "")).strip(),
            narration=str(data.get("narration", "")).strip(),
            style_notes=string_list(data.get("style_notes", [])),
        )

    def validate(self) -> list[str]:
        errors: list[str] = []
        if self.scene_id <= 0:
            errors.append("scene_id must be a positive integer.")
        if not self.title:
            errors.append(f"scene {self.scene_id}: title is required.")
        if not self.culture_element.element_name:
            errors.append(f"scene {self.scene_id}: culture_element.element_name is required.")
        if not self.visual_description:
            errors.append(f"scene {self.scene_id}: visual_description is required.")
        if not self.character_action:
            errors.append(f"scene {self.scene_id}: character_action is required.")
        if not self.narration:
            errors.append(f"scene {self.scene_id}: narration is required.")
        return errors

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["culture_element"] = self.culture_element.to_dict()
        return data


@dataclass(slots=True)
class Storyboard:
    """Complete storyboard output of B."""

    project_title: str
    place_name: str
    tone: StoryboardTone = "文化宣传"
    style: str = "二维手绘童话风"
    total_duration_seconds: float = 45.0
    scenes: list[StoryboardScene] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Storyboard":
        scenes = [StoryboardScene.from_dict(item) for item in data.get("scenes", []) if isinstance(item, dict)]
        return cls(
            project_title=str(data.get("project_title", "")).strip(),
            place_name=str(data.get("place_name", "")).strip(),
            tone=normalize_tone(data.get("tone", "文化宣传")),
            style=str(data.get("style", "二维手绘童话风")).strip() or "二维手绘童话风",
            total_duration_seconds=positive_float(data.get("total_duration_seconds", 45.0), default=45.0),
            scenes=scenes,
        )

    def validate(self) -> list[str]:
        errors: list[str] = []
        if not self.project_title:
            errors.append("project_title is required.")
        if not self.place_name:
            errors.append("place_name is required.")
        if not self.scenes:
            errors.append("at least one scene is required.")
        scene_ids = [scene.scene_id for scene in self.scenes]
        if len(scene_ids) != len(set(scene_ids)):
            errors.append("scene_id values must be unique.")
        for scene in self.scenes:
            errors.extend(scene.validate())
        return errors

    def to_dict(self) -> dict[str, Any]:
        return {
            "project_title": self.project_title,
            "place_name": self.place_name,
            "tone": self.tone,
            "style": self.style,
            "total_duration_seconds": self.total_duration_seconds,
            "scenes": [scene.to_dict() for scene in self.scenes],
        }


@dataclass(slots=True)
class PromptItem:
    """Prompt package passed from B to C."""

    scene_id: int = 0
    prompt_type: PromptType = "image"
    positive_prompt: str = ""
    negative_prompt: str = (
        "photorealistic, 3d render, low quality, blurry, distorted map, wrong text, "
        "extra limbs, bad anatomy, messy composition"
    )
    control_hint: str = "Use map outline or mask as ControlNet constraint."
    style_keywords: list[str] = field(default_factory=lambda: ["2D", "hand-drawn", "fairy-tale", "map-based layout"])
    reference_files: list[str] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "PromptItem":
        return cls(
            scene_id=int(data.get("scene_id", 0)),
            prompt_type=normalize_prompt_type(data.get("prompt_type", "image")),
            positive_prompt=str(data.get("positive_prompt", "")).strip(),
            negative_prompt=str(data.get("negative_prompt", cls().negative_prompt)).strip(),
            control_hint=str(data.get("control_hint", cls().control_hint)).strip(),
            style_keywords=string_list(data.get("style_keywords", ["2D", "hand-drawn", "fairy-tale", "map-based layout"])),
            reference_files=string_list(data.get("reference_files", [])),
        )

    @classmethod
    def from_scene(
        cls,
        scene: StoryboardScene,
        prompt_type: PromptType = "image",
        reference_files: list[str] | None = None,
    ) -> "PromptItem":
        element = scene.culture_element
        keywords = ", ".join(element.visual_keywords + scene.style_notes)
        positive_prompt = (
            f"{scene.visual_description}. "
            f"Character action: {scene.character_action}. "
            f"Map reference: {scene.map_reference}. "
            f"Cultural element: {element.element_name}, {element.category}. "
            f"Visual keywords: {keywords}. "
            f"Style: 2D hand-drawn fairy-tale map animation, local Chinese culture, clean composition."
        )
        return cls(
            scene_id=scene.scene_id,
            prompt_type=prompt_type,
            positive_prompt=positive_prompt,
            reference_files=reference_files or [],
        )

    def validate(self) -> list[str]:
        errors: list[str] = []
        if self.scene_id <= 0:
            errors.append("prompt scene_id must be a positive integer.")
        if not self.positive_prompt:
            errors.append(f"scene {self.scene_id}: positive_prompt is required.")
        return errors

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class NarrationSegment:
    """Narration text passed from B to D."""

    scene_id: int
    text: str
    start_seconds: float = 0.0
    end_seconds: float = 0.0

    @classmethod
    def from_scene(cls, scene: StoryboardScene, start_seconds: float = 0.0) -> "NarrationSegment":
        end_seconds = start_seconds + scene.duration_seconds
        return cls(
            scene_id=scene.scene_id,
            text=scene.narration,
            start_seconds=round(start_seconds, 2),
            end_seconds=round(end_seconds, 2),
        )

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class QualityIssue:
    """One QA issue found in B's output."""

    level: Literal["error", "warning", "info"]
    scene_id: int | None
    message: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class QualityReport:
    """QA report generated by B."""

    passed: bool
    issues: list[QualityIssue] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {"passed": self.passed, "issues": [issue.to_dict() for issue in self.issues]}


def build_prompts_from_storyboard(
    storyboard: Storyboard,
    prompt_type: PromptType = "image",
    reference_files: list[str] | None = None,
) -> list[PromptItem]:
    return [PromptItem.from_scene(scene, prompt_type=prompt_type, reference_files=reference_files) for scene in storyboard.scenes]


def build_narration_from_storyboard(storyboard: Storyboard) -> list[NarrationSegment]:
    segments: list[NarrationSegment] = []
    current = 0.0
    for scene in storyboard.scenes:
        segment = NarrationSegment.from_scene(scene, start_seconds=current)
        segments.append(segment)
        current = segment.end_seconds
    return segments


def string_list(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item).strip() for item in value if str(item).strip()]


def positive_float(value: Any, default: float) -> float:
    try:
        result = float(value)
    except (TypeError, ValueError):
        return default
    return result if result > 0 else default


def normalize_category(value: Any) -> str:
    category = str(value).strip()
    return category if category in CATEGORIES else "产业符号"


def normalize_tone(value: Any) -> StoryboardTone:
    tone = str(value).strip()
    allowed = {"文化宣传", "童话叙事", "旅行导览", "历史讲述"}
    return tone if tone in allowed else "文化宣传"  # type: ignore[return-value]


def normalize_shot_type(value: Any) -> ShotType:
    shot_type = str(value).strip()
    allowed = {"开场", "过渡", "文化展示", "人物行动", "结尾"}
    return shot_type if shot_type in allowed else "文化展示"  # type: ignore[return-value]


def normalize_prompt_type(value: Any) -> PromptType:
    prompt_type = str(value).strip()
    return prompt_type if prompt_type in {"image", "animation"} else "image"  # type: ignore[return-value]
